# These are supported funding model platforms

github: [devinschumacher]
liberapay: devinschumacher
open_collective: devinschumacher
custom: [
  https://boxingundefeated.com,
  https://serp.ai
  https://devinschumacher.com
  https://serp.co
]
